# Generated by Codex on 2026-06-12

from django.db import migrations, models


def seed_system_model_services(apps, schema_editor):
    SystemModelService = apps.get_model('ml', 'SystemModelService')
    defaults = [
        {
            'key': 'llm-preannotation',
            'title': 'LLM 大模型预标注服务',
            'url': 'http://localhost:9090',
            'provider': 'llm',
            'service_type': 'llm',
            'description': '独立部署的大模型预标注后端，面向文本、分类、抽取和多模态预标注场景。',
            'capabilities': ['文本分类预标注', '文本抽取预标注', '多模态预标注', '批量预测'],
            'sort_order': 10,
        },
        {
            'key': 'grounding-dino',
            'title': 'Grounding DINO 视觉预标注服务',
            'url': 'http://localhost:9092',
            'provider': 'grounding_dino',
            'service_type': 'vision',
            'description': '独立部署的 Grounding DINO 开放词表目标检测后端，面向图片框选预标注。',
            'capabilities': ['图片框选预标注', '开放词表检测', '交互式预标注', '批量预测'],
            'sort_order': 20,
        },
    ]

    for item in defaults:
        SystemModelService.objects.update_or_create(
            key=item['key'],
            defaults={
                **item,
                'is_builtin': True,
                'enabled': True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ('ml', '0007_auto_20240314_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                (
                    'service_type',
                    models.CharField(
                        choices=[('vision', 'Vision'), ('llm', 'LLM'), ('custom', 'Custom')],
                        default='custom',
                        max_length=32,
                    ),
                ),
                ('description', models.TextField(blank=True, default='')),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('is_builtin', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_system_model_services, migrations.RunPython.noop),
    ]
