# Generated by Django 5.1.9 on 2025-06-26 20:30

import logging

from django.db import connections
from django.db import migrations
from django.db.utils import OperationalError, ProgrammingError

from core.models import AsyncMigrationStatus
from core.redis import start_job_async_or_sync

logger = logging.getLogger(__name__)

migration_name = '0055_task_proj_octlen_idx_async'

sql_pg_create = (
    'CREATE INDEX CONCURRENTLY IF NOT EXISTS task_proj_octlen_idx '
    'ON task (project_id, octet_length(data::text) DESC) '
    'INCLUDE (id);'
)
sql_pg_drop = 'DROP INDEX CONCURRENTLY IF EXISTS task_proj_octlen_idx;'

# MySQL has no BRIN/INCLUDE/octet_length(data::text); use a simple project filter index.
sql_mysql_create = (
    'CREATE INDEX `task_proj_octlen_idx` ON `task` (`project_id`);'
)
sql_mysql_drop = 'DROP INDEX `task_proj_octlen_idx` ON `task`;'


def forward_migration(migration_name, db_alias):
    migration, created = AsyncMigrationStatus.objects.using(db_alias).get_or_create(
        name=migration_name,
        defaults={'status': AsyncMigrationStatus.STATUS_STARTED},
    )
    if not created:
        return

    logger.info('Start async migration %s', migration_name)
    conn = connections[db_alias]
    cursor = conn.cursor()

    if conn.vendor == 'postgresql':
        cursor.execute(sql_pg_create)
    elif conn.vendor == 'mysql':
        try:
            cursor.execute(sql_mysql_create)
        except (OperationalError, ProgrammingError) as e:
            if not e.args or e.args[0] != 1061:
                raise
    else:
        logger.info('Skipping index creation for vendor %s', conn.vendor)

    migration.status = AsyncMigrationStatus.STATUS_FINISHED
    migration.save(using=db_alias)
    logger.info('Async migration %s complete', migration_name)


def backward_migration(migration_name, db_alias):
    migration = AsyncMigrationStatus.objects.using(db_alias).create(
        name=migration_name,
        status=AsyncMigrationStatus.STATUS_STARTED,
    )
    logger.info('Start revert of async migration %s', migration_name)
    conn = connections[db_alias]
    cursor = conn.cursor()

    if conn.vendor == 'postgresql':
        cursor.execute(sql_pg_drop)
    elif conn.vendor == 'mysql':
        try:
            cursor.execute(sql_mysql_drop)
        except (OperationalError, ProgrammingError) as e:
            if not e.args or e.args[0] != 1091:
                raise
    else:
        logger.info('Skipping index drop for vendor %s', conn.vendor)

    migration.status = AsyncMigrationStatus.STATUS_FINISHED
    migration.save(using=db_alias)
    logger.info('Async migration %s revert complete', migration_name)


def forwards(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == 'sqlite':
        logger.info('Skipping async index creation for SQLite')
        return
    db_alias = schema_editor.connection.alias
    start_job_async_or_sync(forward_migration, migration_name=migration_name, db_alias=db_alias)


def backwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    start_job_async_or_sync(backward_migration, migration_name=migration_name, db_alias=db_alias)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tasks', '0054_add_brin_index_updated_at'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
