# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0036_task_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_group',
            field=models.CharField(
                blank=True,
                default='',
                help_text='标注模板库分组名称（与 annotation_templates/groups.txt 及选中模板的 group 一致）',
                max_length=255,
                verbose_name='template group',
            ),
        ),
    ]
